apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: ns-jenkins
  annotations:
    kubernetes.io/ingress.class: 'nginx'

spec:
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
  rules:
  - host: opyter.iptime.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-leader-svc
            port:
              number: 80
