apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  #namespace: ns-project
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
    #ingress.bluemix.net/rewrite-path: "serviceName=app-service rewrite=/"
spec:
  rules:
  - host: abc.sample.com
    http:
      paths:
      - path: /jenkins
        backend:
          serviceName: batch-visualizer-backend-provider-service
          servicePort: 30000