kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-system
  labels:
    app: ingress-nginx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: ingress-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: ingress-system

